stages:
  - pull
  - build
  - lint
  - push
  - deploy
  - cleanup

before_script:
  - docker login -u ngorbach -p IctSiM12 registry.gitlab.propulsion-home.ch/nico-stephan-gorbach/week-8/backend:latest

pull:
  stage: pull
  tags:
  - digital-ocean
  script:
    - docker pull registry.gitlab.propulsion-home.ch/nico-stephan-gorbach/week-8/backend:latest