
stages:
  - pull
  - build
  - lint
  - push
  - deploy
  - cleanup

before_script:
  - docker login -u ngorbach -p IctSiM12 registry.gitlab.propulsion-home.ch/nico-stephan-gorbach/week-8/backend:latest

pull:
  stage: pull
  tags:
  - digital-ocean
  script:
    - docker pull registry.gitlab.propulsion-home.ch/nico-stephan-gorbach/week-8/backend:latest
    
build:
  include: https://gitlab.propulsion-home.ch/nico-stephan-gorbach/week-8/backend/blob/master/
  stage: build
  tags:
  - digital-ocean
  script:
    - docker build --file=Dockerfile_backend --tag=registry.gitlab.propulsion-home.ch/nico-stephan-gorbach/week-8/backend:latest --cache-from="$CI_REGISTRY_IMAGE":latest .