stages:
  - pull-backend
  - build
  - lint
  - push
  - deploy
  - cleanup

before_script:
  - docker login -u ngorbach -p IctSiM12 registry.gitlab.propulsion-home.ch/nico-stephan-gorbach/week-8/backend:latest

pull-backend-image:
  stage: pull
  tags:
  - digital-ocean
  script:
    - docker pull registry.gitlab.propulsion-home.ch/nico-stephan-gorbach/week-8/backend:latest
    
pull-frontend-image:
  stage: pull
  tags:
  - digital-ocean
  script:
    - docker pull registry.gitlab.propulsion-home.ch/nico-stephan-gorbach/week-8/frontend:latest
    
deploy:
  stage: deploy
  when: manual
  tags:
  - digital_ocean
  script:
    - docker-compose -f docker-compose.prod.yml pull
    - docker-compose -f docker-compose.prod.yml down --remove-orphans
    - docker-compose -f docker-compose.prod.yml up -d