stages:
  - pull_backend_dockerimage
  - pull_frontend_dockerimage
  - deploy

pull_backend_dockerimage:
  stage: pull_backend_dockerimage
  tags:
  - digital-ocean
  script:
    - docker login -u ngorbach -p IctSiM12 registry.gitlab.propulsion-home.ch/nico-stephan-gorbach/week-8/backend:latest
    - docker pull registry.gitlab.propulsion-home.ch/nico-stephan-gorbach/week-8/backend:latest
    
pull_frontend_dockerimage:
  stage: pull_frontend_dockerimage
  tags:
  - digital-ocean
  script:
    - docker login -u ngorbach -p IctSiM12 registry.gitlab.propulsion-home.ch/nico-stephan-gorbach/week-8/frontend:latest
    - docker pull registry.gitlab.propulsion-home.ch/nico-stephan-gorbach/week-8/frontend:latest
    
deploy:
  stage: deploy
  when: manual
  tags:
  - digital_ocean
  script:
    - docker-compose -f docker-compose.prod.yml pull
    - docker-compose -f docker-compose.prod.yml down --remove-orphans
    - docker-compose -f docker-compose.prod.yml up -d