version:  '3'

services:
  postgres:
    image: postgres:latest
    env_file:
      - ./envs/dev.env
    volumes:
      - postgres:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80" # only http
      - "443:443" # https
    volumes:
      - frontend:/frontend
      - ./nginx:/etc/nginx/conf.d
      - static-files:/static-files
      - media-files:/media-files
#      - /etc/letsencrypt:/etc/letsencrypt

  backend:
    image: registry.gitlab.propulsion-home.ch/nico-stephan-gorbach/week-8/backend
    restart: always
    env_file:
      - ./envs/dev.env
    command: 'sh /scripts/run.sh'
      
  frontend:
    image: registry.gitlab.propulsion-home.ch/nico-stephan-gorbach/week-8/frontend
    restart: always
    command: 'sh /scripts/run.sh'
    volumes:
      - frontend:/frontend/build
      - media-files:/media-files
      - static-files:/static-files

volumes:
  media-files:
  static-files:
  postgres:
  frontend: