version: '3'

services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    env_file: ./envs/dev.env
    volumes:
      - postgres:/var/lib/postgresql/data

  backend:
    image: motion_app:latest
    restart: always
    env_file:
      - ./envs/dev.env
    ports:
      - 8000:8000
    depends_on:
      - postgres
    volumes:
      - ./backend:/backend
    command: bash -c "python manage.py migrate && python manage.py runserver 0:8000"

volumes:
  postgres:
